### ISSUE TITLE
Flaky e2e test: SendActionItemToUsersViaEmailTest

### ISSUE THREAD

**Issue by vanderhoop** [stride-nyc/remote_retro#396]
As an open source maintainer,
I want the [`SendActionItemToUsersViaEmailTest`](https://github.com/stride-nyc/remote_retro/blob/master/test/features/send_action_item_to_users_via_email_test.exs) test to pass (or fail, for that matter) deterministically,
So that I can merge pull requests without .

**By Way of Explanation:** we occasionally see this failure crop up on CircleCI, but to this point we have not seen the failure in local builds:

```
** (Wallaby.QueryError) Expected to find 1, visible button 'Yes' but 0, visible buttons were found.
     
     stacktrace:
       (wallaby) lib/wallaby/browser.ex:471: Wallaby.Browser.find/2
       (remote_retro) test/support/test_helpers.ex:46: RemoteRetro.TestHelpers.click_and_confirm/2
       test/features/send_action_item_to_users_via_email_test.exs:20: (test)
```

__Acceptance Criteria:__

- [x] investigate the cause of flakiness within the `SendActionItemToUsersViaEmailTest` and implement a fix

__Helpful Links:__

- [Wallaby Screenshots Documentation](https://github.com/keathley/wallaby/#windows-and-screenshots)
- [First failure appearance on CircleCI](https://circleci.com/gh/stride-nyc/remote_retro/963)
- [Second failure appearance on CircleCI](https://circleci.com/gh/stride-nyc/remote_retro/996)
- [Third failure appearance on CircleCI](https://circleci.com/gh/stride-nyc/remote_retro/1030)

**Comment by vanderhoop** [comment]
for posterity: this appears to have been caused by the stage progression button being housed on the lower third, which shifts up from offscreen. we handled this by disabling css animations in during end-to-end tests, so that the lower third is where it needs to be when the webdriver attempts to click it. see cc9604d41a08ffd038da60da0edc5616a9471887
