### ISSUE TITLE
Wallaby had an internal issue with HTTPoison when running mix e2e

### ISSUE THREAD

**Issue by kamok** [stride-nyc/remote_retro#503]
As a developer,
I want to run e2e tests.

Trace
```
Executing end-to-end tests...

	Note: browser logs will written to `browser_logs.log`

Including tags: [:feature_test]
Excluding tags: [:test, :skip]



  1) test when an idea already exists in a retro the immediate update of ideas as they are changed/saved (RetroIdeaRealtimeUpdateTest)
     test/features/retro_idea_realtime_update_test.exs:31
     ** (RuntimeError) Wallaby had an internal issue with HTTPoison
     stacktrace:
       (wallaby) lib/wallaby/httpclient.ex:32: Wallaby.HTTPClient.make_request/4
       (wallaby) lib/wallaby/experimental/chrome.ex:64: Wallaby.Experimental.Chrome.start_session/1
       (wallaby) lib/wallaby.ex:80: Wallaby.start_session/1
       (remote_retro) test/support/test_helpers.ex:45: RemoteRetro.TestHelpers.new_authenticated_browser_session/1
       (remote_retro) test/support/integration_case.ex:47: RemoteRetro.IntegrationCase.__ex_unit_setup_0/1
       (remote_retro) test/support/integration_case.ex:1: RemoteRetro.IntegrationCase.__ex_unit__/2
       test/features/retro_idea_realtime_update_test.exs:1: RetroIdeaRealtimeUpdateTest.__ex_unit__/2

.........
2018-10-17 10:16:04.610 chromedriver[52594:666860] pid(52594)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2018-10-17 10:16:04.610 chromedriver[52594:666860] pid(52594)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!

Finished in 12.0 seconds
10 tests, 1 failure
```
Googling these error messages; will post fix if I can find it. Followed README already

**Comment by kamok** [comment]
@vanderhoop This is most likely a chromedriver wallaby version issue. Can you give me your configuration so I can just use those versions?

**Comment by kamok** [comment]
Not a problem with versions in terms of OS or package versions. Tests are passing with a restart of machine.

However, still seeing a ton of lines like this:
```
2018-10-17 11:18:56.680 chromedriver[3717:27104] pid(3717)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2018-10-17 11:18:56.680 chromedriver[3717:27104] pid(3717)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
2018-10-17 11:18:56.680 chromedriver[3717:27104] pid(3717)/euid(501) is calling TIS/TSM in non-main thread environment, ERROR : This is NOT allowed. Please call TIS/TSM in main thread!!!
```

**Comment by kamok** [comment]
Probably an issue with Wallaby.Experimental.Chrome

**Comment by kamok** [comment]
It stopped showing up for some reason. Should close if nobody else can reproduce.

**Comment by kamok** [comment]
Closing this, opening one for the TIS/TSM error instead.
